export const transactionData = [
    {
        id: 1,
        tanggal: "13/1/2025",
        vendor: "Dapur Kodam III Siliwangi",
        sekolah: "SMP Negeri 1 Kota Bandung",
        pks: "File PKS",
        bast: "File BAST",
        bap: "File BAP",
        status: "Selesai",
    },
    {
        id: 2,
        tanggal: "13/1/2025",
        vendor: "Dapur Kodam III Siliwangi",
        sekolah: "SMP Negeri 1 Kota Bandung",
        pks: "File PKS",
        bast: "File BAST",
        bap: "File BAP",
        status: "Selesai",
    },
    {
        id: 3,
        tanggal: "13/1/2025",
        vendor: "Dapur Kodam III Siliwangi",
        sekolah: "SMP Negeri 1 Kota Bandung",
        pks: "File PKS",
        bast: "File BAST",
        bap: "File BAP",
        status: "Selesai",
    },
    {
        id: 4,
        tanggal: "13/1/2025",
        vendor: "Dapur Kodam III Siliwangi",
        sekolah: "SMP Negeri 1 Kota Bandung",
        pks: "File PKS",
        bast: "File BAST",
        bap: "File BAP",
        status: "Selesai",
    },
    {
        id: 5,
        tanggal: "13/1/2025",
        vendor: "Dapur Kodam III Siliwangi",
        sekolah: "SMP Negeri 1 Kota Bandung",
        pks: "File PKS",
        bast: "File BAST",
        bap: "File BAP",
        status: "Selesai",
    },
    {
        id: 6,
        tanggal: "20/1/2025",
        vendor: "Dapur Kodam III Siliwangi",
        sekolah: "SMP Negeri 1 Kota Bandung",
        pks: "File PKS",
        bast: "File BAST",
        bap: "NA",
        status: "Belum Dibayar",
    },
    {
        id: 7,
        tanggal: "20/1/2025",
        vendor: "Dapur Kodam III Siliwangi",
        sekolah: "SMP Negeri 1 Kota Bandung",
        pks: "File PKS",
        bast: "File BAST",
        bap: "NA",
        status: "Belum dibayar",
    },
    {
        id: 8,
        tanggal: "20/1/2025",
        vendor: "Dapur Kodam III Siliwangi",
        sekolah: "SMP Negeri 1 Kota Bandung",
        pks: "File PKS",
        bast: "File BAST",
        bap: "NA",
        status: "Belum dibayar",
    },
    {
        id: 9,
        tanggal: "20/1/2025",
        vendor: "Dapur Kodam III Siliwangi",
        sekolah: "SMP Negeri 1 Kota Bandung",
        pks: "File PKS",
        bast: "File BAST",
        bap: "NA",
        status: "Belum dibayar",
    },
    {
        id: 10,
        tanggal: "20/1/2025",
        vendor: "Dapur Kodam III Siliwangi",
        sekolah: "SMP Negeri 1 Kota Bandung",
        pks: "File PKS",
        bast: "File BAST",
        bap: "NA",
        status: "Belum dibayar",
    },
  ]